defaults:
  - dev: local

# force re-generate dataset files
u: false
# max evaluations for hyperopt search
max_evals: 1
description: ""

# preconditioner epochs (only for 'pre-' pipelines)
pre_epochs: 40
full_epochs: 1
target: train

# Additive Schwarz flag (defaults to Multiplicative Schwarz)
ASM: false
gamma_algo: none
optim: Adam
ll_resolution: 0
gamma_lr: 0.01
gamma_strat: direct

seed: 42
epochs: 100
