# quiet
q: false
# force re-generate dataset files
u: false
# max evaluations for hyperopt search
max_evals: 1

# preconditioner epochs (only for 'pre-' pipelines)
pre_epochs: 40
# Additive Schwarz flag (defaults to Multiplicative Schwarz)
ASM: false

seed: 42
epochs: 100
